<a href="https://colab.research.google.com/github/glenda2912/Tous12/blob/main/Feminicides_(exam_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**1.Intro**

In [23]:
# Libraries

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

##**2.Import**

In [24]:
# Save the path o the file 

p= '/content/fm2.xlsx'

#Read the file 
d = pd.read_excel(p)


#Check
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Años       25 non-null     float64
 1   Country    25 non-null     object
 2   Hom        25 non-null     float64
 3   Country.1  39 non-null     object
 4   Year       39 non-null     int64
 5   Homxboy    39 non-null     int64
 6   Country.2  38 non-null     object
 7   Year.1     38 non-null     float64
 8   Poverty    38 non-null     float64
dtypes: float64(4), int64(2), object(3)
memory usage: 2.9+ KB

In [25]:
#Check the fist entries
d.head()

,Años,Country,Hom,Country.1,Year,Homxboy,Country.2,Year.1,Poverty
0,2017.0,Brasil,1582.0,Argentina,2017,172,Brasil,2017.0,114.1
1,2017.0,Perú,116.0,Chile,2017,44,Brasil,2017.0,110.6
2,2017.0,Honduras,235.0,Colombia,2017,144,Brasil,2018.0,113.4
3,2017.0,México,742.0,Costa Rica,2017,14,Brasil,2018.0,113.0
4,2018.0,México,893.0,Ecuador,2017,85,Brasil,2019.0,114.7

In [4]:
#Check the last entries 
d.tail()

    Años      País  Valor
20  2021    Brasil   1900
21  2021  Colombia    210
22  2021  Honduras    234
23  2021    México   1015
24  2021      Perú    136

# **3.Cleaning**

## Column Names

In [5]:
# Change Time for Year 
d.rename(columns = {"Años": "Year"}, inplace = True)

# Change County Name
d.rename(columns = {"País": "Country"}, inplace = True)

#Change Value
d.rename(columns = {"Valor": "Hom"}, inplace = True)

#Check
d.head()

   Year   Country   Hom
0  2017    Brasil  1582
1  2017      Perú   116
2  2017  Honduras   235
3  2017    México   742
4  2018    México   893

## Delete columns

**My data base is so short so i'm not going to delete the column**

## A few more things

In [6]:
# (Optional) Duplicate the dataframe

pp = d

In [7]:
# Duplicate year variable 
pp["Year_str"] = pp["Year"].astype(str)

#Check
pp.head()

   Year   Country   Hom Year_str
0  2017    Brasil  1582     2017
1  2017      Perú   116     2017
2  2017  Honduras   235     2017
3  2017    México   742     2017
4  2018    México   893     2018

# **4.Indexing**

In [8]:
# Create an index
idx = pd.MultiIndex.from_product([pp['Country'].unique(),
                                  range(pp.Year.min(),pp.Year.max()+1)],
                                  names= ['Country', 'Year'])

#Reindex the dataframe 
pp = pp.set_index(['Year','Country'])

#Check 
pp.head()

                Hom Year_str
Year Country
2017 Brasil    1582     2017
     Perú       116     2017
     Honduras   235     2017
     México     742     2017
2018 México     893     2018

# **5.Basic Statistics**

In [9]:
# By variable 
pp[['Hom']].describe()

               Hom
count    25.000000
mean    657.680000
std     654.890431
min     116.000000
25%     187.000000
50%     234.000000
75%     948.000000
max    2048.000000

In [10]:
# By variable and by year 
pp[['Hom']].groupby('Year').describe()

       Hom
     count   mean         std    min    25%    50%     75%     max
Year
2017   5.0  576.6  612.963131  116.0  208.0  235.0   742.0  1582.0
2018   5.0  671.2  733.586873  150.0  218.0  228.0   893.0  1867.0
2019   5.0  722.6  808.831441  148.0  177.0  295.0   945.0  2048.0
2020   5.0  619.0  639.410275  137.0  187.0  227.0   948.0  1596.0
2021   5.0  699.0  760.685875  136.0  210.0  234.0  1015.0  1900.0

In [11]:
# By variable and by country
pp[['Hom']].groupby('Country').describe()

           Hom
         count    mean         std     min     25%     50%     75%     max
Country
Brasil     5.0  1798.6  203.176770  1582.0  1596.0  1867.0  1900.0  2048.0
Colombia   5.0   202.0   20.161845   177.0   187.0   208.0   210.0   228.0
Honduras   5.0   241.8   30.507376   218.0   227.0   234.0   235.0   295.0
México     5.0   908.6  102.709785   742.0   893.0   945.0   948.0  1015.0
Perú       5.0   137.4   13.520355   116.0   136.0   137.0   148.0   150.0

# **6. Filters and pivots**

## Simple Filters

In [29]:
# Filter by country name and save it 
brasil = pp.filter(like= 'Brasil', axis=0)
print(brasil)

               Hom Year_str
Year Country
2017 Brasil   1582     2017
2018 Brasil   1867     2018
2019 Brasil   2048     2019
2020 Brasil   1596     2020
2021 Brasil   1900     2021

In [30]:
# Filter by year name and save it 
y20 = pp.filter(like= '2019', axis=0)
print(y20)

                Hom Year_str
Year Country
2019 Brasil    2048     2019
     México     945     2019
     Perú       148     2019
     Honduras   295     2019
     Colombia   177     2019

## Simple Pivots

In [32]:
# Creating is dataframe with the tie-serie of hom 
ts_Hom = d.pivot(index   = 'Year',
                 columns = 'Country',
                 values  = 'Hom')
print(ts_Hom)

ValueError: ignored

# **7. Basic Line/Bar Grap**

In [33]:
# Line Graph the homicides in brasil 2017-2021
fig = px.line(brasil, x = 'Year_str', y='Hom')


# Change title
fig.update_layout(title = 'Homicides in Brasil 2017-2021',
                  title_font_size = 30,
                  title_x = 0.5)

# Change Axis
fig.update_xaxes(title = 'Years', title_font_size = 20)
fig.update_yaxes(title = 'Dates', title_font_size = 20)

fig.show()

In [27]:
# Bar Graph the homicides in brasil 2017-2021

fig = px.bar(brasil, x = "Year_str", y='Hom')

# Change title
fig.update_layout(title = 'Homicides in Brasil 2017-2021',
                  title_font_size = 30,
                  title_x = 0.5,
                  yaxis_range = [1500,2500])

# Change Axis
fig.update_xaxes(title = 'Homicides', title_font_size = 20)
fig.update_yaxes(title = 'Years', title_font_size = 20)

fig.show()

In [28]:
# Create a figure with secondary axis
fig = make_subplots(specs = [[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x = brasil['Year_str'], y = brasil['Hom'], name = 'Hom.'),
    secondary_y = False, 
)
fig.add_trace(
    go.Scatter(x = brasil['Year_str'], y = brasil['Homxboy'], name = 'Homicides for ex or boyfriend'),
    secondary_y = True, 
)

fig.show()

KeyError: ignored

## All countries and one variable

In [ ]:
fig = px.line()