<a href="https://colab.research.google.com/github/glenda2912/Tous12/blob/main/Health_(exam_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**1.Intro**

In [64]:
# Libraries

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

##**2.Import**

In [65]:
# Save the path o the file 

d= '/content/Population.xlsx'

#Read the file 
d = pd.read_excel(d)


#Check
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   Country Name                                                                 210 non-null    object
 1   Year                                                                         210 non-null    int64
 2   Adolescent fertility rate (births per 1,000 women ages 15-19) [SP.ADO.TFRT]  210 non-null    object
 3   Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS]        210 non-null    object
 4   Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]                        210 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.3+ KB

In [66]:
#Check the fist entries
d.head()

,Country Name,Year,"Adolescent fertility rate (births per 1,000 women ages 15-19) [SP.ADO.TFRT]",Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]"
0,Antigua and Barbuda,2016,43.6256,..,5.662
1,Antigua and Barbuda,2017,42.782,100,5.746
2,Antigua and Barbuda,2018,41.831,..,5.787
3,Antigua and Barbuda,2019,40.88,..,5.865
4,Antigua and Barbuda,2020,39.929,99,5.961

In [67]:
#Check the last entries 
d.tail()

,Country Name,Year,"Adolescent fertility rate (births per 1,000 women ages 15-19) [SP.ADO.TFRT]",Births attended by skilled health staff (% of total) [SH.STA.BRTC.ZS],"Death rate, crude (per 1,000 people) [SP.DYN.CDRT.IN]"
205,Virgin Islands (U.S.),2016,32.259,..,7.5
206,Virgin Islands (U.S.),2017,28.887,..,7.7
207,Virgin Islands (U.S.),2018,27.6482,..,7.9
208,Virgin Islands (U.S.),2019,26.4094,..,8.2
209,Virgin Islands (U.S.),2020,25.1706,..,8.4

# **3.Cleaning**

## Column Names

In [39]:
# Change Country Name
d.rename(columns = {"Country Name": "country"}, inplace = True)

# Change Year
d.rename(columns = {"Year": "year"}, inplace = True)

#Change Adolescent fertility
d.rename(columns = {"adolescent fertility": "fertility"}, inplace = True)

#Change Adolescent fertility
d.rename(columns = {"adolescent fertility": "fertility"}, inplace = True)

#Change Adolescent fertility
d.rename(columns = {"adolescent fertility": "fertility"}, inplace = True)
#Check
d.head()

              country   year fertility births  death  year_str
0  Antigua and Barbuda  2016   43.6256      ..  5.662     2016
1  Antigua and Barbuda  2017    42.782     100  5.746     2017
2  Antigua and Barbuda  2018    41.831      ..  5.787     2018
3  Antigua and Barbuda  2019     40.88      ..  5.865     2019
4  Antigua and Barbuda  2020    39.929      99  5.961     2020

## Delete columns

**My data base is so short so i'm not going to delete the column**

## A few more things

In [54]:
# (Optional) Duplicate the dataframe

dd = d

In [55]:
# Duplicate year variable 
dd["year_str"] = dd["year"].astype(str)

#Check
dd.head()

              country   year adolescent fertility births  death  year_str
0  Antigua and Barbuda  2016              43.6256      ..  5.662     2016
1  Antigua and Barbuda  2017               42.782     100  5.746     2017
2  Antigua and Barbuda  2018               41.831      ..  5.787     2018
3  Antigua and Barbuda  2019                40.88      ..  5.865     2019
4  Antigua and Barbuda  2020               39.929      99  5.961     2020

# **4.Indexing**

In [57]:
# Create an index

#Reindex the dataframe 
dd = dd.set_index(['country','year'])

#Check 
dd.head()

KeyError: ignored

# **5.Basic Statistics**

In [49]:
# By variable 
dd[['fertility','death']].describe()

KeyError: ignored

In [12]:
# By variable and by year 
pp[['Hom']].groupby('Year').describe()

       Hom
     count        mean         std   min    25%    50%     75%     max
Year
2017   6.0  361.666667  606.111101   0.0  40.25  162.0  238.75  1582.0
2018   6.0  420.333333  716.521784   0.0  51.75  189.0  250.50  1867.0
2019   6.0  441.166667  793.114725   0.0  51.25  162.5  235.50  2048.0
2020   6.0  374.166667  604.443684  31.0  66.50  162.0  235.00  1596.0
2021   6.0  423.833333  728.089120  22.0  67.00  173.0  225.75  1900.0

In [13]:
# By variable and by country
pp[['Hom']].groupby('Country').describe()

            Hom
          count    mean         std     min     25%     50%     75%     max
Country
Argentina   5.0   248.8   10.545141   231.0   249.0   251.0   255.0   258.0
Brasil      5.0  1798.6  203.176770  1582.0  1596.0  1867.0  1900.0  2048.0
Chile       5.0    17.4   23.828554     0.0     0.0     0.0    43.0    44.0
Colombia    5.0   202.0   20.161845   177.0   187.0   208.0   210.0   228.0
Panamá      5.0    21.2    6.016644    15.0    19.0    19.0    22.0    31.0
Perú        5.0   137.4   13.520355   116.0   136.0   137.0   148.0   150.0

# **6. Filters and pivots**

## Simple Filters

In [14]:
# Filter by country name and save it 
brasil = pp.filter(like= 'Brasil', axis=0)
print(brasil)

               Hom  HomxBoy  Punery Year_str
Year Country
2017 Brasil   1582        0   110.6     2017
2018 Brasil   1867        0   113.0     2018
2019 Brasil   2048        0   114.9     2019
2020 Brasil   1596        0   116.7     2020
2021 Brasil   1900        0   124.2     2021

In [15]:
# Filter by year name and save it 
y20 = pp.filter(like= '2019', axis=0)
print(y20)

                 Hom  HomxBoy  Punery Year_str
Year Country
2019 Argentina   255      181     0.0     2019
     Brasil     2048        0   114.9     2019
     Chile         0       46     0.0     2019
     Colombia    177      128   123.9     2019
     Panamá       19        5   126.2     2019
     Perú        148       98   108.3     2019

## Simple Pivots

In [16]:
# Creating is dataframe with the tie-serie of hom 
ts_Hom = d.pivot(index   = 'Year',
                 columns = 'Country',
                 values  = 'Hom')
print(ts_Hom)

Country  Argentina  Brasil  Chile  Colombia  Panamá  Perú
Year
2017           249    1582      0       208      15   116
2018           258    1867      0       228      19   150
2019           255    2048      0       177      19   148
2020           251    1596     43       187      31   137
2021           231    1900     44       210      22   136

# **7. Basic Line/Bar Grap**

In [22]:
# Line Graph the homicides in brasil 2017-2021
fig = px.line(brasil, x = 'Year_str', y='Hom')


# Change title
fig.update_layout(title = 'Homicides in Brasil 2017-2021',
                  title_font_size = 30,
                  title_x = 0.5)

# Change Axis
fig.update_xaxes(title = 'Years', title_font_size = 20)
fig.update_yaxes(title = 'Homicides', title_font_size = 20)

fig.show()

In [18]:
# Bar Graph the homicides in brasil 2017-2021

fig = px.bar(brasil, x = "Year_str", y='Hom')

# Change title
fig.update_layout(title = 'Homicides in Brasil 2017-2021',
                  title_font_size = 30,
                  title_x = 0.5,
                  yaxis_range = [1500,2500])

# Change Axis
fig.update_xaxes(title = 'Homicides', title_font_size = 20)
fig.update_yaxes(title = 'Years', title_font_size = 20)

fig.show()

## Two y-axis

In [23]:
# Create a figure with secondary axis
fig = make_subplots(specs = [[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x = brasil['Year_str'], y = brasil['Hom'], name = 'Homicides.'),
    secondary_y = False, 
)

fig.add_trace(
    go.Scatter(x = brasil['Year_str'], y = brasil['Homxboy'], name = 'Homicides for ex or boyfriend'),
    secondary_y = True, 
)

fig.show()

KeyError: ignored

In [ ]:
# Create a figure with secondary axis
fig = make_subplots(specs = [[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Bar(x = colombia['year_str'], y = colombia['life'], name = 'Life Exp.'),
    secondary_y = False, 
)

fig.add_trace(
    go.Scatter(x = colombia['year_str'], y = colombia['gdp'], name = 'GDP per Capita'),
    secondary_y = True, 
)

fig.show()

## All countries and one variable

In [ ]:
fig = px.line(dd,
              x = "year_str",
              y = 'life',
              color = dd.index.get_level_values(0))
fig.show()

# **8. Basic Pie Charts**

In [ ]:
fig = px.pie(y20, values = 'gdp', 
             names = y20.index.get_level_values(0))
fig.show()